{application,piqi,
             [{description,"Piqi Library"},
              {vsn,"0.5.6"},
              {modules,[piqi,piqi_app,piqi_piqi,piqi_rpc_piqi,piqi_sup,
                        piqi_tools,piqi_tools_piqi,piqic_erlang_ext,piqirun,
                        piqirun_ext,piqirun_props,piqirun_tests]},
              {registered,[piqi_tools,piqi_sup]},
              {applications,[kernel,stdlib]},
              {mod,{piqi_app,[]}},
              {env,[{worker_pool_size,1}]}]}.
